# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/conc',
                'doc_host': 'https://polsci.github.io',
                'git_url': 'https://github.com/polsci/conc',
                'lib_path': 'conc'},
  'syms': {'conc.core': {'conc.core.foo': ('core.html#foo', 'conc/core.py')}}}
