"""Functionality for collocation analysis."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/74_collocates.ipynb.

# %% ../nbs/74_collocates.ipynb 3
from __future__ import annotations
import numpy as np
import time
import polars as pl
from fastcore.basics import patch
import math

# %% auto 0
__all__ = ['Collocates']

# %% ../nbs/74_collocates.ipynb 4
from .corpus import Corpus
from .result import Result
from .core import logger, PAGE_SIZE

# %% ../nbs/74_collocates.ipynb 5
class Collocates:
	""" Class for collocation analysis reporting. """
	def __init__(self,
			  corpus:Corpus # Corpus instance
			  ): 
		self.corpus = corpus

