# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/73_keyness.ipynb.

# %% auto 0
__all__ = ['Keyness']

# %% ../nbs/73_keyness.ipynb 3
import numpy as np
import time
import polars as pl
from fastcore.basics import patch
import math

# %% ../nbs/73_keyness.ipynb 4
from .corpus import Corpus
from .result import Result
from .core import logger, PAGE_SIZE

# %% ../nbs/73_keyness.ipynb 5
class Keyness:
	""" Class for keyness analysis reporting. """
	def __init__(self,
			  corpus:Corpus # Corpus instance
			  ): 
		self.corpus = corpus

