project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/polsci/conc"
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - text: "Introduction to Conc"
        href: index.ipynb
      - section: Tutorials
        contents: tutorials/*
      - section: Explanations
        contents: explanations/*
      - section: API
        contents: api/*
      - section: Development
        contents: development/*

metadata-files: [nbdev.yml]