name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # PIN Python to 3.10 or 3.11 to avoid nbdev breakage with entry_points
          python-version: '3.10'
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install Dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          # PIN nbdev and related fastai tools to a known working version
          pip install nbdev==2.3.35 fastcore==1.7.29 execnb==0.1.12 ghapi==1.0.6
          # PIN Quarto to a stable release if you use it (optional)
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.deb
          sudo dpkg -i quarto-1.4.550-linux-amd64.deb
          # Install your package and dev dependencies
          test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
          # Build docs
          nbdev_docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_docs
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          publish_branch: gh-pages

