name: CI
on:  [workflow_dispatch, pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      # start changes from default CI https://github.com/AnswerDotAI/workflows/blob/master/nbdev-ci/action.yml
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' # hard-coding - but may need to change in future
      - name: Install dependencies
        run: pip install spacy
      - name: Install spaCy English model
        run: python -m spacy download en_core_web_sm
      - name: Install Conc
        run: pip install -e ".[dev]"
      - name: Download and build sample corpora for tests
        run: conc_build_sample_corpora ~/data/ ~/data/conc-test-corpora/
      # end changes from default CI
      - uses: fastai/workflows/nbdev-ci@master
